#!/usr/bin/env python3
"""
RotaAssist — scikit-learn DecisionTreeClassifier → pure Lua converter

Traverses the internal tree structure and emits a Lua file with nested
if/else logic that the WoW Lua VM can execute at near-zero cost.

Usage (standalone):
    python sklearn2lua.py --model model.pkl --features features.json \
                          --output DT.lua --spec-id 577

Typically called programmatically from train_decision_tree.py.
"""

import argparse
import datetime
import json
import pickle
import sys
from typing import List, Optional

import numpy as np


def tree_to_lua(
    clf,
    feature_names: List[str],
    class_names: List[str],
    spec_id: int,
    output_path: str,
    accuracy: float = 0.0,
):
    """Export a fitted DecisionTreeClassifier to a Lua file."""

    tree = clf.tree_
    max_depth = clf.get_depth()
    n_nodes = tree.node_count
    today = datetime.date.today().isoformat()

    lines: List[str] = []

    def _add(text: str):
        lines.append(text)

    # ---- Header ----
    _add(f"--- RotaAssist Decision Tree (specID {spec_id})")
    _add(f"--- Auto-generated by sklearn2lua.py on {today}")
    _add("--- DO NOT EDIT MANUALLY - regenerate with training/train_decision_tree.py")
    _add(f"--- Tree depth: {max_depth}, Nodes: {n_nodes}, Training accuracy: {accuracy:.1%}")
    _add("-- 自動生成の決定木ファイル / 自动生成的决策树文件，请勿手动编辑")
    _add("")
    _add("local _, NS = ...")
    _add("local RA = NS.RA")
    _add("local DT = {}")
    _add("")
    _add(f"DT.specID = {spec_id}")
    _add(f'DT.generatedDate = "{today}"')
    _add(f"DT.treeDepth = {max_depth}")
    _add(f"DT.trainingAccuracy = {accuracy:.4f}")
    _add("")

    # ---- Recursive tree traversal ----
    def _recurse(node_id: int, depth: int):
        indent = "    " * (depth + 1)

        # Safety: prevent excessively deep nesting
        if depth > 15:
            # Fallback: return nil for uncertainty
            _add(f"{indent}return nil")
            return

        left = tree.children_left[node_id]
        right = tree.children_right[node_id]

        if left == right:  # Leaf node
            values = tree.value[node_id][0]
            total = values.sum()
            best_idx = int(np.argmax(values))
            confidence = values[best_idx] / total if total > 0 else 0.0

            if confidence < 0.3:
                _add(f"{indent}return nil  -- low confidence {confidence:.2f}")
            else:
                spell_id = int(class_names[best_idx])
                _add(f"{indent}return {{spellID={spell_id}, confidence={confidence:.4f}}}")
        else:
            feat_idx = tree.feature[node_id]
            threshold = tree.threshold[node_id]
            feat_name = feature_names[feat_idx]

            # For spellID features, round threshold to integer
            if "SpellID" in feat_name or "Recommendation" in feat_name:
                threshold_str = str(int(round(threshold)))
            else:
                threshold_str = f"{threshold:.4f}"

            _add(f"{indent}if features.{feat_name} <= {threshold_str} then")
            _recurse(left, depth + 1)
            _add(f"{indent}else")
            _recurse(right, depth + 1)
            _add(f"{indent}end")

    # ---- Build function body ----
    _add("--- Evaluate the decision tree with given features.")
    _add("--- @param features table")
    _add("--- @return table|nil {spellID=number, confidence=number}")
    _add("function DT.Evaluate(features)")
    _recurse(0, 0)
    _add("end")
    _add("")
    _add("RA.DecisionTrees = RA.DecisionTrees or {}")
    _add(f"RA.DecisionTrees[{spec_id}] = DT")
    _add("")

    with open(output_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))

    print(f"Lua decision tree written to {output_path} "
          f"(depth={max_depth}, nodes={n_nodes}, acc={accuracy:.1%})")


# -----------------------------------------------------------------------
# Standalone CLI
# -----------------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(description="sklearn tree → Lua")
    parser.add_argument("--model", required=True, help="Pickled sklearn model")
    parser.add_argument("--features", required=True, help="JSON list of feature names")
    parser.add_argument("--output", required=True, help="Output .lua path")
    parser.add_argument("--spec-id", type=int, required=True)
    args = parser.parse_args()

    with open(args.model, "rb") as f:
        clf = pickle.load(f)

    with open(args.features, "r") as f:
        feature_names = json.load(f)

    class_names = [str(c) for c in clf.classes_]
    tree_to_lua(clf, feature_names, class_names, args.spec_id, args.output)


if __name__ == "__main__":
    main()
